# Generated by Django 6.0.1 on 2026-01-22 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="image_name",
            new_name="image",
        ),
    ]
